services:
  # Backend Service
  - type: web
    name: mern-stack-hero-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://ArockiaDass:Eventflow%40123@cluster0.kniyc4z.mongodb.net/event-management?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        value: "25b87b64246eb3a1e74bcb4e524ce642e488b5f1dcf7ed15ac47b372c8bf1368a723b220694ed0289d05da1179f1c856c3cc6ce93be2c8fd4ee8255a1f4bc612"
      - key: NODE_VERSION
        value: "20"

  # Frontend Service
  - type: web
    name: mern-stack-hero-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "20"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
